// <auto-generated />
using System;
using Infrasctructure.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrasctructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220403121817_Add_action_column_to_topic_cycle_table")]
    partial class Add_action_column_to_topic_cycle_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Domain.entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoneQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Domain.entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.entities.SubjectCycle", b =>
                {
                    b.Property<int>("SubjectCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubjectCycleId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectCycles");
                });

            modelBuilder.Entity("Domain.entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lawsCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("lawsItem")
                        .HasColumnType("TEXT");

                    b.Property<string>("readingCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("readingItem")
                        .HasColumnType("TEXT");

                    b.Property<string>("revisionCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("revisionItem")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Domain.entities.TopicCycle", b =>
                {
                    b.Property<int>("TopicCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TopicCycleId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicCycles");
                });

            modelBuilder.Entity("Domain.entities.Question", b =>
                {
                    b.HasOne("Domain.entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.entities.Subject", b =>
                {
                    b.HasOne("Domain.entities.Project", "Project")
                        .WithMany("Subjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.entities.SubjectCycle", b =>
                {
                    b.HasOne("Domain.entities.Subject", "Subject")
                        .WithMany("SubjectCycles")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.entities.Topic", b =>
                {
                    b.HasOne("Domain.entities.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.entities.TopicCycle", b =>
                {
                    b.HasOne("Domain.entities.Topic", "Topic")
                        .WithMany("TopicCycles")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.entities.Project", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.entities.Subject", b =>
                {
                    b.Navigation("SubjectCycles");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Domain.entities.Topic", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TopicCycles");
                });
#pragma warning restore 612, 618
        }
    }
}
